---


# Deploy Search Head Common Configuration to Search head cluster deployer

- block:
  - name: "Deploy search_head common configuration to search_head cluster master"
    copy: src={{ platform_repos_home }}/{{ env_dir }}/search_head/{{ item }} dest={{ splunk_etc }}/shcluster/apps
    with_items:
      - sh_common_config